# Generated by Django 2.0.2 on 2018-02-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('tweet_id', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('friends', models.PositiveIntegerField(default=0)),
                ('listed', models.PositiveIntegerField(default=0)),
                ('favourites', models.PositiveIntegerField(default=0)),
                ('statuses', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField()),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Twitter User',
                'verbose_name_plural': 'Twitter Users',
            },
        ),
        migrations.AddField(
            model_name='tweet',
            name='twitter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='tweeter.TwitterUser'),
        ),
    ]
