# Generated by Django 2.0.2 on 2018-02-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0003_auto_20180207_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
